### ISSUE TITLE
Search resources by name or location name

### ISSUE THREAD

**Issue by joaotomaspinheiro** [Goncalo-Marques/ecomap#91]
Allow to search by (filtering by one or more): 
  - Container
  - Route
  - Truck
 
Requirements:
  - Sort
  - Pagination
  - Filter by geolocation and resource name
  - Postgres `ILIKE` search

**Comment by Goncalo-Marques** [comment]
This issue is unnecessary since the same behavior can be replicated in the list endpoint of each resource domain.
